# Generated by Django 6.0.5 on 2026-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_climat', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'climate_types',
            },
        ),
    ]
