# Generated by Django 6.0.5 on 2026-05-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_source', models.CharField(max_length=150)),
                ('base_url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('api_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_sources',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unite', models.CharField(max_length=100)),
                ('symbole', models.CharField(blank=True, max_length=50, null=True)),
                ('type_variable', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.AlterField(
            model_name='climatetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_region', models.CharField(max_length=150, unique=True)),
                ('chef_lieu', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('climate_type', models.ForeignKey(blank=True, db_column='climate_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.climatetype')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nom_variable', models.CharField(max_length=150)),
                ('type_variable', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.unit')),
            ],
            options={
                'db_table': 'variables',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_station', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.region')),
            ],
            options={
                'db_table': 'weather_stations',
            },
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('temperature_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feels_like_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_report',
            },
        ),
        migrations.CreateModel(
            name='WeatherHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('temperature_2m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relative_humidity_2m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apparent_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rain', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed_10m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_10m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('surface_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_day', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.apisource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_hourly',
            },
        ),
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_2m_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_2m_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('relative_humidity_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rain_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed_10m_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_speed_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_gusts_10m_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sunshine_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uv_index_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.apisource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_daily',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('type_alerte', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['nom_region'], name='idx_regions_nom'),
        ),
        migrations.AddIndex(
            model_name='weatherreport',
            index=models.Index(fields=['station'], name='idx_weather_report_station'),
        ),
        migrations.AddIndex(
            model_name='weatherreport',
            index=models.Index(fields=['date'], name='idx_weather_report_date'),
        ),
        migrations.AddIndex(
            model_name='weatherhourly',
            index=models.Index(fields=['station'], name='idx_weather_hourly_station'),
        ),
        migrations.AddIndex(
            model_name='weatherhourly',
            index=models.Index(fields=['date_heure'], name='idx_weather_hourly_datetime'),
        ),
        migrations.AddIndex(
            model_name='weatherdaily',
            index=models.Index(fields=['station'], name='idx_weather_daily_station'),
        ),
        migrations.AddIndex(
            model_name='weatherdaily',
            index=models.Index(fields=['date'], name='idx_weather_daily_date'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['station'], name='idx_alerts_station'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['date_heure'], name='idx_alerts_datetime'),
        ),
    ]
