# Generated by Django 6.0.5 on 2026-05-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_apisource_unit_alter_climatetype_description_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
